In [15]:
# numpy provides fast alternatives to math operations in Python
import numpy as np 


In [16]:
# most common way to work with numbers in numpy is throught ndarray objects,similar to python list and can have m mumber of dimension in addition , it suppport fast mathematical operation 

In [17]:
#scalar involved more in numpy than in python , numpy let you specify signed and unsigned types and sizes
# scalar is more inportant becouse every tensor you make will consist of scalrs, like when you create numpy array must have the same scalar type 
arr = np.array(5)
arr.shape

()

In [18]:
# this (). indicates that it has zero dimensions shape.
# since it is treated as a scalar even tho it is in an array lets do some mathethematical operations on it 
arr = arr + 3
arr

8

In [20]:
# as you can see it adds 3 to our scalar of value 5

#Vector
# to create it you can pass python list to array function 
vec = np.array([1,2,3])
vec.shape

(3,)

In [23]:
# as you can see above vec is one dimmension vector , to acccess its content use indices as normal array 
vec[1]

2

In [24]:
# numpy also support advanced indexing techniques , like returning up to 1th inidces 
vec[:1]

array([1])

In [26]:
#Matrices 
# to create a matrix we need to do as we did creating  vector but for now providing python list of lists , instead of one list  
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat.shape

(3, 3)

In [28]:
#as you see above we created two dimension tensor(matrix)

#accessing matrix information is the same as vector but providing additional index value
#lets get 7 in the above matrix 
mat[2][0]

7

In [30]:
#tensors 
# tensors is also vector or matrix but beside that ,it can have many dimessions. for example now lets create one 
tens = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

tens.shape

(3, 3, 2, 1)

In [34]:
# you can access the element assing more indices 
tens[1][2][1][0]

12

In [36]:
#changing shapes 
# sometimes you need to change shapes lets say from vector to matrix and so on 
v = np.array([1,2,3,4])
v.shape

(4,)

In [39]:
#lets say we want to change this vecor to matrix of (1,4), we can do so using reshape funstion 
reshaped = v.reshape(1,4)

In [40]:
#now calling shape can give you a matrix shape (1,4)
reshaped.shape

(1, 4)

In [43]:
#here are some other arternative to use reshape fucntionalities 
x = v[None, :]
x = v[:, None]
x

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
#element wise matrix 
# lets say you want to add 5 to every elemet in matrix  you might need to write loops that loop into the vector or matrix , but with numpy its easier 
values = [1,2,3,4,5]
values = np.array(values) + 5
values

In [ ]:
#Creating that array may seem odd, but normally you'll be storing your data in ndarrays anyway. So if you already had an ndarray named values, you could have just done:

values += 5

In [ ]:
x = np.multiply(some_array, 5)
x = some_array * 5

In [ ]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])

b = np.array([[2,4],[6,8]])
b
# displays the following result:
# array([[2, 4],
#        [6, 8]])

a + b
# displays the following result
#      array([[ 3,  7],
#  

In [ ]:
a = np.array([[1,3],[5,7]])
a
# displays the following result:
# array([[1, 3],
#        [5, 7]])
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c
# displays the following result:
# array([[2, 3, 6],
#        [4, 5, 9],
#        [1, 8, 7]])

a.shape
# displays the following result:
#  (2, 2)

c.shape
# displays the following result:
#  (3, 3)

a + c
# displays the following error:
# ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [ ]:
m = np.array([[1,2,3],[4,5,6]])
m
# displays the following result:
# array([[1, 2, 3],
#        [4, 5, 6]])

n = m * 0.25
n
# displays the following result:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

np.multiply(m, n)   # equivalent to m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a.shape
# displays the following result:
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b
# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b.shape
# displays the following result:
# (4, 3)

c = np.matmul(a, b)
c
# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
c.shape
# displays the following result:
# (2, 3)

In [ ]:
np.matmul(b, a)
# displays the following error:
# ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
a = np.array([[1,2],[3,4]])
a
# displays the following result:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # you can call `dot` directly on the `ndarray`
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

In [ ]:
#transpose  , Getting the transpose of a matrix is really easy in NumPy. Simply access its T attribute. There is also a transpose() function which returns the same thing, but you’ll rarely see that used anywhere because typing T is so much easier. :)

For example:
#you can safelly use transpose in multiplying a matrix if the data of the original matrix are arranged as rows 

m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m
# displays the following result:
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])

m.T
# displays the following result:
# array([[ 1,  5,  9],
#        [ 2,  6, 10],
#        [ 3,  7, 11],
#        [ 4,  8, 12]])

In [ ]:
m_t = m.T
m_t[3][1] = 200
m_t
# displays the following result:
# array([[ 1,   5, 9],
#        [ 2,   6, 10],
#        [ 3,   7, 11],
#        [ 4, 200, 12]])

m
# displays the following result:
# array([[ 1,  2,  3,   4],
#        [ 5,  6,  7, 200],
#        [ 9, 10, 11,  12]])


In [ ]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs
# displays the following result:
# array([[-0.27,  0.45,  0.64,  0.31]])

inputs.shape
# displays the following result:
# (1, 4)

weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights
# displays the following result:
# array([[ 0.02 ,  0.001, -0.03 ,  0.036],
#        [ 0.04 , -0.003,  0.025,  0.009],
#        [ 0.012, -0.045,  0.28 , -0.067]])

weights.shape
# displays the following result:
# (3, 4)

In [ ]:
np.matmul(inputs, weights)
# displays the following error:
# ValueError: shapes (1,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [ ]:
np.matmul(inputs, weights.T)
# displays the following result:
# array([[-0.01299,  0.00664,  0.13494]])

In [ ]:
np.matmul(weights, inputs.T)
# displays the following result:
# array([[-0.01299],# 
#        [ 0.00664],
#        [ 0.13494]])